name: Execution of Scraper Australian Seeds
run-name: ${{ github.actor }} is executing Scraper Australian Seeds

on:
  workflow_dispatch

jobs:
  run-scraper:
    name: Run Scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run JAR
        run: java -jar ScraperAustralianSeeds.jar
      - name: Upload scraper content
        uses: actions/upload-artifact@v3
        with:
          name: scraper-info-outputs-${{ github.actor }}
          path: outputs
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: scraper-info-outputs-${{ github.actor }}
      - name: Test artifact download
        run: ls -R
